version: '3.8'

services:
  web:
    image: nginx:1.23-alpine
    container_name: app-web
    working_dir: /application
    volumes:
      - ./env/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - app-dev
    ports:
      - ${EXTERNAL_WEBSERVER_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - php
      - database


  php:
    build:
      context: env/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    container_name: app-php
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
      - ./env/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: app-db
    environment:
      - PGPASSWORD=${DOCKER_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
    ports:
        - ${DOCKER_DB_EXTERNAL_PORT:-5433}:5432
    volumes:
      - app-pgsql-data:/var/lib/postgresql/data
    networks:
        - app-dev
    restart: unless-stopped

networks:
  app-dev:
    driver: bridge

volumes:
  app-pgsql-data:
    name: app-pgsql-data